name: swu-check scheduled run

on:
  schedule:
    - cron: '10 13 * * *'
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug file structure
        run: |
          echo "Root directory:"
          ls -la
          echo "Searching main.py:"
          find . -name "main.py"

      - name: Run main.py
        env:
          TZ: Asia/Shanghai
          SWU_USERNAME: ${{ secrets.SWU_USERNAME }}
          SWU_PASSWORD: ${{ secrets.SWU_PASSWORD }}
        run: python main.py
